pipeline{
	agent any
	stages{
		stage('Compile Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
				bat 'mvn compile'
				}
			}							
		}	
		stage('build Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
				bat 'mvn install'
				}
			}							
		}	
	}
}