pipeline{
	agent any	
	stages{
		stage('Compile Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					dir("${env.WORKSPACE}/CalegoryService"){
						bat 'mvn compile'
					}						
				}
			}							
		}	
		stage('build Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
				bat 'mvn install'
				}
			}							
		}	
	}
}