pipeline{
	agent any	
	stages{
		stage('Compile Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					dir("${env.WORKSPACE}/ProductService"){
						bat 'mvn compile'
					}						
				}
			}							
		}
		stage('Test Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					dir("${env.WORKSPACE}/ProductService"){
						bat 'mvn test'
					}						
				}
			}							
		}
		stage('build Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
					dir("${env.WORKSPACE}/ProductService"){
						bat 'mvn install'	
					}
				
				}
			}							
		}		
	}
}